---
# Tasks role geth: tạo user geth, tạo thư mục, deploy systemd service

- name: Tạo system user 'geth' nếu chưa tồn tại (non-login)
  ansible.builtin.user:
    name: geth
    system: yes
    shell: /usr/sbin/nologin
    create_home: yes
    home: /var/lib/geth
  tags: [geth, app]

- name: Tạo thư mục data cho geth
  ansible.builtin.file:
    path: /var/lib/geth
    state: directory
    owner: geth
    group: geth
    mode: '0750'
  tags: [geth, app]

- name: Tạo thư mục keystore cho geth
  ansible.builtin.file:
    path: /var/lib/geth/keystore
    state: directory
    owner: geth
    group: geth
    mode: '0700'
  tags: [geth, app, pci3]

- name: Deploy unit file for geth (systemd) từ template
  ansible.builtin.template:
    src: geth.service.j2
    dest: /etc/systemd/system/geth.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd and restart geth
  tags: [geth, app]

- name: Ensure geth systemd service enabled and started
  ansible.builtin.service:
    name: geth
    state: started
    enabled: yes
  tags: [geth, app]

