---
# roles/05_audit/tasks/main.yml
# D. Quản trị & review (Scanning & Compliance)

# --- Periodic vulnerability scanning (PCI Req 6, 11) ---

- name: "[Cleanup] Remove duplicate 'universe' repo file"
  # File này được tạo bởi task [Prereq] cũ
  # Nó gây ra lỗi "configured multiple times"
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/archive_ubuntu_com_ubuntu.list"
    state: absent
  notify: Run apt update (to clear cache) # <--- Gọi handler mới
  tags: [audit, openscap, pci6, pci11]

- name: Install OpenSCAP scanner (ONLY)
  # Cài đặt CHỈ công cụ quét. Các gói luật (ssg) không có sẵn cho 24.04
  ansible.builtin.apt:
    name:
      - openscap-scanner
      # - ssg-utils # <--- TẠM THỜI COMMENT LẠI VÌ KHÔNG TÌM THẤY
      # - scap-security-guide # <--- TẠM THỜI COMMENT LẠI VÌ KHÔNG TÌM THẤY
    state: present
  tags: [audit, openscap, pci6, pci11]

- name: Run OpenSCAP scan (v2 - CACHE BREAKER)
  # Đổi tên task và bỏ 'args: warn: false' để phá cache
  ansible.builtin.shell: |
    oscap xccdf eval \
    --profile cis \
    --report /tmp/oscap_report-{{ ansible_date_time.iso8601 }}.html \
    /usr/share/xml/scap/ssg/content/ssg-ubuntu2404-ds.xml
  register: scan_result
  changed_when: scan_result.rc != 0
  failed_when: false # Không dừng playbook ngay cả khi quét thất bại
  tags: [audit, openscap, pci6, pci11]

- name: Display scan results path
  # Hiển thị đường dẫn đến file report
  ansible.builtin.debug:
    msg: |
      [THÀNH CÔNG] Đã chạy OpenSCAP.
      Return Code: {{ scan_result.rc }} (Lưu ý: 2 = Non-Compliant)
      Report HTML: /tmp/oscap_report-{{ ansible_date_time.iso8601 }}.html
  tags: [audit, openscap, pci6, pci11]

# --- Automated compliance checks (InSpec) (PCI Req 11, 12) ---
- name: Display note about InSpec
  ansible.builtin.debug:
    msg: |
      [LƯU Ý] Tích hợp InSpec (ComplianceAsCode)
      là một pipeline CI/CD phức tạp, chạy từ máy Ansible/GitLab Runner,
      kết nối vào máy Geth qua SSH (giống như Ansible).
      Nó nằm ngoài phạm vi của việc cấu hình máy Geth.
  tags: [audit, inspec, pci11, pci12]
