---
# ===============================================================
# Role: 03_monitoring
# Purpose: Implement monitoring & detection for PCI-DSS compliance
# Components: Auditd, AIDE, Centralized Logging (rsyslog), Fail2ban
# ===============================================================

# ---------------------------
# PHẦN 1: Auditd - Nhật ký kiểm toán hệ thống
# ---------------------------
- name: Install auditd and audispd-plugins
  ansible.builtin.apt:
    name:
      - auditd
      - audispd-plugins
    state: present
  tags: [monitoring, auditd]

- name: Deploy custom audit rules for PCI & Geth
  ansible.builtin.copy:
    dest: /etc/audit/rules.d/99-pci-geth.rules
    content: |
      -w /etc/passwd -p wa -k user_group_changes
      -w /etc/group -p wa -k user_group_changes
      -w /etc/shadow -p wa -k user_group_changes
      -w /etc/sudoers -p wa -k sudoers_changes
      -w /etc/ssh/sshd_config -p wa -k sshd_config_changes
      -w /usr/bin/sudo -p x -k sudo_exec
      -w /bin/su -p x -k su_exec
      -w {{ geth_keystore_path }}/ -p rwa -k geth_keystore_access
    mode: '0640'
  notify: Restart auditd
  tags: [monitoring, auditd]

- name: Ensure auditd service is enabled and running
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: yes
  tags: [monitoring, auditd]


# ---------------------------
# PHẦN 2: AIDE - File Integrity Monitoring
# ---------------------------
- name: Install AIDE package
  ansible.builtin.apt:
    name: aide
    state: present
  tags: [monitoring, aide]

- name: Check if AIDE database exists
  ansible.builtin.stat:
    path: /var/lib/aide/aide.db.gz
  register: aide_db_final
  tags: [monitoring, aide]

- name: Remove old or corrupted AIDE temporary files
  ansible.builtin.file:
    path: /var/lib/aide/aide.db.new
    state: absent
  when: not aide_db_final.stat.exists
  tags: [monitoring, aide]

- name: Initialize AIDE database (slow process)
  ansible.builtin.command: aideinit
  args:
    creates: /var/lib/aide/aide.db.gz
  async: 3600
  poll: 15
  when: not aide_db_final.stat.exists
  tags: [monitoring, aide]

- name: Schedule daily AIDE check
  ansible.builtin.cron:
    name: "Daily AIDE integrity check"
    hour: "5"
    job: "/usr/bin/aide.wrapper --check"
    user: root
    cron_file: aide-daily-check
  tags: [monitoring, aide]


# ---------------------------
# PHẦN 3: Centralized Logging (rsyslog)
# ---------------------------
- name: Ensure rsyslog is installed
  ansible.builtin.apt:
    name: rsyslog
    state: present
  tags: [monitoring, logging]

- name: Configure rsyslog to forward logs to SIEM
  ansible.builtin.copy:
    dest: /etc/rsyslog.d/60-forward-to-siem.conf
    content: |
      *.* @@{{ siem_server_ip }}:{{ siem_server_port }}
    mode: '0644'
  notify: Restart rsyslog
  tags: [monitoring, logging]

- name: Ensure rsyslog is enabled and running
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes
  tags: [monitoring, logging]


# ---------------------------
# PHẦN 4: Fail2ban - Phòng chống tấn công SSH brute-force
# ---------------------------
- name: Install Fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
  tags: [monitoring, fail2ban]

- name: Configure Fail2ban local jail for SSH
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      maxretry = 3
      [sshd]
      enabled = true
    mode: '0644'
  notify: Restart fail2ban
  tags: [monitoring, fail2ban]

- name: Ensure Fail2ban service is enabled and running
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes
  tags: [monitoring, fail2ban]

