---
# ===============================================================
# Role: 06_compliance
# Purpose: Verify compliance & generate audit evidence for PCI-DSS / DCI-PSS
# Components: Service checks, permission validation, config audit, evidence report
# ===============================================================

# ---------------------------
# PHẦN 1: Kiểm tra trạng thái dịch vụ bảo mật
# ---------------------------
- name: Gather service facts
  ansible.builtin.service_facts:
  tags: [compliance, services]

- name: Verify security services are active
  ansible.builtin.assert:
    that:
      - "'auditd.service' in ansible_facts.services"
      - ansible_facts.services['auditd.service'].state == "running"
      - ansible_facts.services['fail2ban.service'].state == "running"
      - ansible_facts.services['rsyslog.service'].state == "running"
      - ansible_facts.services['geth.service'].state == "running"
    fail_msg: "Một hoặc nhiều dịch vụ bảo mật chưa hoạt động!"
    success_msg: "Tất cả dịch vụ bảo mật hoạt động bình thường."
  tags: [compliance, services]


# ---------------------------
# PHẦN 2: Kiểm tra cấu hình SSH Hardening
# ---------------------------
- name: Check SSH configuration for compliance
  ansible.builtin.shell: |
    grep -E "^(PermitRootLogin|PasswordAuthentication|AllowGroups)" /etc/ssh/sshd_config
  register: ssh_conf_check
  changed_when: false
  tags: [compliance, ssh]

- name: Validate SSH configuration parameters
  ansible.builtin.assert:
    that:
      - "'PermitRootLogin no' in ssh_conf_check.stdout"
      - "'PasswordAuthentication no' in ssh_conf_check.stdout"
    fail_msg: "SSH chưa được cấu hình an toàn!"
    success_msg: "SSH cấu hình tuân thủ (root login & password auth disabled)."
  tags: [compliance, ssh]


# ---------------------------
# PHẦN 3: Kiểm tra quyền truy cập thư mục nhạy cảm
# ---------------------------
- name: Check sensitive directories permissions
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - /var/lib/geth
    - /var/backups/geth
  register: sensitive_dirs
  tags: [compliance, permissions]

- name: Validate permissions on sensitive directories
  ansible.builtin.assert:
    that:
      - item.stat.pw_name in ["root", "geth"]
      - item.stat.mode | int(base=8) <= 750
    fail_msg: "Thư mục {{ item.stat.path }} có quyền truy cập quá rộng!"
    success_msg: "Thư mục {{ item.stat.path }} bảo mật đúng chuẩn."
  loop: "{{ sensitive_dirs.results }}"
  loop_control:
    label: "{{ item.stat.path }}"
  tags: [compliance, permissions]


# ---------------------------
# PHẦN 4: Kiểm tra cron backup & log
# ---------------------------
- name: Check if backup cron job exists
  ansible.builtin.stat:
    path: /etc/cron.d/geth-backup
  register: cron_exists
  tags: [compliance, backup]

- name: Assert cron backup file presence
  ansible.builtin.assert:
    that:
      - cron_exists.stat.exists
    fail_msg: "Cron backup chưa được thiết lập!"
    success_msg: "Cron backup tồn tại."
  tags: [compliance, backup]

# Tìm file log CŨ hơn 1 ngày (để fail nếu có)
- name: Verify if any backup log older than 1 day exists
  ansible.builtin.find:
    paths: /var/backups/geth
    patterns: "backup.log"
    age_stamp: mtime
    age: 1d
  register: old_backup_logs
  tags: [compliance, backup]

# Nếu KHÔNG có log cũ → PASS (nghĩa là log được cập nhật trong vòng 24h)
- name: Assert backup log is fresh (within last 24h)
  ansible.builtin.assert:
    that:
      - old_backup_logs.matched == 0
    fail_msg: "Log backup không được cập nhật trong 24h qua!"
    success_msg: "Log backup mới nhất trong vòng 24h."
  tags: [compliance, backup]



# ---------------------------
# PHẦN 5: Sinh báo cáo kiểm thử tuân thủ
# ---------------------------
- name: Create compliance report directory
  ansible.builtin.file:
    path: /var/log/compliance
    state: directory
    mode: '0750'
  tags: [compliance, report]

- name: Generate compliance summary report
  ansible.builtin.copy:
    dest: /var/log/compliance/compliance_report.txt
    mode: '0640'
    content: |
      ======================================================
      🧾 PCI-DSS Compliance Verification Report
      Host: {{ inventory_hostname }}
      Date: {{ ansible_date_time.date }} {{ ansible_date_time.time }}
      ======================================================

      Dịch vụ bảo mật: OK
      SSH cấu hình an toàn: OK
      Phân quyền thư mục nhạy cảm: OK
      Cron backup & log: OK

      [Auto-generated by Role: 07_compliance]
  tags: [compliance, report]

