---
# Handlers cho role 03_monitoring
- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
